---
title: "R Notebook"
output: html_notebook
---

```{r}
library(rjson)
library(rvest)
library(stringr)
library(httr)
```

```{r}
regions = c("occident", "japan", "korea", "chinese")
```

```{r}
if (!file.exists("data_unfiltered")) {
  dir.create("data_unfiltered")
}
if (!file.exists("data_filtered")) {
  dir.create("data_filtered")
}
for (r in regions) {
  if (!file.exists(paste("data_unfiltered/data_", r, sep = ""))) {
    dir.create(paste("data_unfiltered/data_", r, sep = ""))
  }
  if (!file.exists(paste("data_filtered/data_", r, sep = ""))) {
    dir.create(paste("data_filtered/data_", r, sep = ""))
  }
}
```

```{r}
for (r in regions) {
  dat = fromJSON(file=paste("meta_data/search_subjects_", r, ".json", sep = ""))$subjects
  urls = sapply(dat, function(d) {d$url})
  titles = sapply(dat, function(d) {d$title})
  df = data.frame(urls, titles)
  for (i in 1:length(df$urls)) {
    if (file.exists(paste("data_unfiltered/data_", r, "/", df$titles[i], ".html", sep = ""))) {
      next
    }
    print(df$titles[i])
    html = readLines(df$urls[i])
    writeLines(html, paste("data_unfiltered/data_", r, "/", df$titles[i], ".html", sep = ""))
    Sys.sleep(runif(1, 1, 4))
  }
}
```

```{r}
for (r in regions) {
  files = list.files(paste("data_unfiltered/data_", r, sep = ""))
  for (f in files) {
    print(f)
    path = paste("data_unfiltered/data_", r, "/", f, sep = "")
    html_str = readLines(path, encoding="UTF-8")
    html = read_html(paste(html_str, collapse = ""), encoding="UTF-8")
    cond1 = (html %>% html_elements(".year") %>% html_text() %in% c("(2021)", "(2022)"))
    cond2 = html %>% html_elements("div#info") %>% html_text() %>% str_detect("上映日期:.*?(中国大陆)")
    print(c(cond1, cond2))
    if (cond1 & cond2) {
      writeLines(html_str, paste("data_filtered/data_", r, "/", f, sep = ""), useBytes = T)
    }
  }
}
```

